name: Java CI with Gradle

on:
  push:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        java: [17]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew build

      - name: Capture build artifacts
        id: upload
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: |
            build/libs/
            !build/libs/*-dev.jar
            !build/libs/*-sources.jar

  release:
    name: Release Project
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        id: download
        uses: actions/download-artifact@v2
        with:
          name: Artifacts

      - name: View content
        run: ls -R

      - name: Get filename as env variable
        run: file=$(echo *.jar); echo "file_name=${file}" >> $GITHUB_ENV

      - name: Get version as env variable
        run: file=$(echo *.jar);ver=${file%.*};ver=${ver##replenish-}; echo "version=${ver}" >> $GITHUB_ENV

      - name: Create release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.version }}
          release_name: Release ${{ env.version }}

      - name: Upload release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./${{ env.file_name }}
          asset_name: ${{ env.file_name }}
          asset_content_type: application/java-archive
